name: Test & Deploy
on:
  push:
    branches:
      - main
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@main

      # Zip Dockerfile for upload
      - name: Generate Deployment Package
        run: zip -r deploy.zip * -x "**.git**"
        
      - name: Get timestamp
        uses: gerred/actions/current-time@main
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@main
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: odoo-dev-app
          environment_name: OdooDevApp-env
          version_label: "the-dev-deployment-${{ steps.format-time.outputs.replaced }}"
          region: us-east-1
          deployment_package: deploy.zip
